// Code generated by Kitex v0.4.4. DO NOT EDIT.

package socialityservice

import (
	"context"
	siciality "github.com/CyanAsterisk/TikGok/server/shared/kitex_gen/siciality"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return socialityServiceServiceInfo
}

var socialityServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "SocialityService"
	handlerType := (*siciality.SocialityService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Action":        kitex.NewMethodInfo(actionHandler, newSocialityServiceActionArgs, newSocialityServiceActionResult, false),
		"FollowingList": kitex.NewMethodInfo(followingListHandler, newSocialityServiceFollowingListArgs, newSocialityServiceFollowingListResult, false),
		"FollowerList":  kitex.NewMethodInfo(followerListHandler, newSocialityServiceFollowerListArgs, newSocialityServiceFollowerListResult, false),
		"FriendList":    kitex.NewMethodInfo(friendListHandler, newSocialityServiceFriendListArgs, newSocialityServiceFriendListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "siciality",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*siciality.SocialityServiceActionArgs)
	realResult := result.(*siciality.SocialityServiceActionResult)
	success, err := handler.(siciality.SocialityService).Action(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialityServiceActionArgs() interface{} {
	return siciality.NewSocialityServiceActionArgs()
}

func newSocialityServiceActionResult() interface{} {
	return siciality.NewSocialityServiceActionResult()
}

func followingListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*siciality.SocialityServiceFollowingListArgs)
	realResult := result.(*siciality.SocialityServiceFollowingListResult)
	success, err := handler.(siciality.SocialityService).FollowingList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialityServiceFollowingListArgs() interface{} {
	return siciality.NewSocialityServiceFollowingListArgs()
}

func newSocialityServiceFollowingListResult() interface{} {
	return siciality.NewSocialityServiceFollowingListResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*siciality.SocialityServiceFollowerListArgs)
	realResult := result.(*siciality.SocialityServiceFollowerListResult)
	success, err := handler.(siciality.SocialityService).FollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialityServiceFollowerListArgs() interface{} {
	return siciality.NewSocialityServiceFollowerListArgs()
}

func newSocialityServiceFollowerListResult() interface{} {
	return siciality.NewSocialityServiceFollowerListResult()
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*siciality.SocialityServiceFriendListArgs)
	realResult := result.(*siciality.SocialityServiceFriendListResult)
	success, err := handler.(siciality.SocialityService).FriendList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialityServiceFriendListArgs() interface{} {
	return siciality.NewSocialityServiceFriendListArgs()
}

func newSocialityServiceFriendListResult() interface{} {
	return siciality.NewSocialityServiceFriendListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Action(ctx context.Context, req *siciality.DouyinRelationActionRequest) (r *siciality.DouyinRelationActionResponse, err error) {
	var _args siciality.SocialityServiceActionArgs
	_args.Req = req
	var _result siciality.SocialityServiceActionResult
	if err = p.c.Call(ctx, "Action", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowingList(ctx context.Context, req *siciality.DouyinRelationFollowListRequest) (r *siciality.DouyinRelationFollowListResponse, err error) {
	var _args siciality.SocialityServiceFollowingListArgs
	_args.Req = req
	var _result siciality.SocialityServiceFollowingListResult
	if err = p.c.Call(ctx, "FollowingList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, req *siciality.DouyinRelationFollowerListRequest) (r *siciality.DouyinRelationFollowerListResponse, err error) {
	var _args siciality.SocialityServiceFollowerListArgs
	_args.Req = req
	var _result siciality.SocialityServiceFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, req *siciality.DouyinRelationFriendListRequest) (r *siciality.DouyinRelationFriendListResponse, err error) {
	var _args siciality.SocialityServiceFriendListArgs
	_args.Req = req
	var _result siciality.SocialityServiceFriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
