// Code generated by Kitex v0.4.4. DO NOT EDIT.

package socialityservice

import (
	"context"
	sociality "github.com/CyanAsterisk/TikGok/server/shared/kitex_gen/sociality"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Action(ctx context.Context, req *sociality.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationActionResponse, err error)
	FollowingList(ctx context.Context, req *sociality.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationFollowListResponse, err error)
	FollowerList(ctx context.Context, req *sociality.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationFollowerListResponse, err error)
	FriendList(ctx context.Context, req *sociality.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationFriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialityServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialityServiceClient struct {
	*kClient
}

func (p *kSocialityServiceClient) Action(ctx context.Context, req *sociality.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, req)
}

func (p *kSocialityServiceClient) FollowingList(ctx context.Context, req *sociality.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowingList(ctx, req)
}

func (p *kSocialityServiceClient) FollowerList(ctx context.Context, req *sociality.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kSocialityServiceClient) FriendList(ctx context.Context, req *sociality.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *sociality.DouyinRelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}
