// Code generated by Kitex v0.4.4. DO NOT EDIT.

package interactionserver

import (
	"context"
	interaction "github.com/CyanAsterisk/TikGok/server/shared/kitex_gen/interaction"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return interactionServerServiceInfo
}

var interactionServerServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "InteractionServer"
	handlerType := (*interaction.InteractionServer)(nil)
	methods := map[string]kitex.MethodInfo{
		"Favorite":                  kitex.NewMethodInfo(favoriteHandler, newInteractionServerFavoriteArgs, newInteractionServerFavoriteResult, false),
		"GetFavoriteVideoIdList":    kitex.NewMethodInfo(getFavoriteVideoIdListHandler, newInteractionServerGetFavoriteVideoIdListArgs, newInteractionServerGetFavoriteVideoIdListResult, false),
		"Comment":                   kitex.NewMethodInfo(commentHandler, newInteractionServerCommentArgs, newInteractionServerCommentResult, false),
		"GetCommentList":            kitex.NewMethodInfo(getCommentListHandler, newInteractionServerGetCommentListArgs, newInteractionServerGetCommentListResult, false),
		"GetVideoInteractInfo":      kitex.NewMethodInfo(getVideoInteractInfoHandler, newInteractionServerGetVideoInteractInfoArgs, newInteractionServerGetVideoInteractInfoResult, false),
		"BatchGetVideoInteractInfo": kitex.NewMethodInfo(batchGetVideoInteractInfoHandler, newInteractionServerBatchGetVideoInteractInfoArgs, newInteractionServerBatchGetVideoInteractInfoResult, false),
		"GetUserInteractInfo":       kitex.NewMethodInfo(getUserInteractInfoHandler, newInteractionServerGetUserInteractInfoArgs, newInteractionServerGetUserInteractInfoResult, false),
		"BatchGetUserInteractInfo":  kitex.NewMethodInfo(batchGetUserInteractInfoHandler, newInteractionServerBatchGetUserInteractInfoArgs, newInteractionServerBatchGetUserInteractInfoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "interaction",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func favoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerFavoriteArgs)
	realResult := result.(*interaction.InteractionServerFavoriteResult)
	success, err := handler.(interaction.InteractionServer).Favorite(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerFavoriteArgs() interface{} {
	return interaction.NewInteractionServerFavoriteArgs()
}

func newInteractionServerFavoriteResult() interface{} {
	return interaction.NewInteractionServerFavoriteResult()
}

func getFavoriteVideoIdListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerGetFavoriteVideoIdListArgs)
	realResult := result.(*interaction.InteractionServerGetFavoriteVideoIdListResult)
	success, err := handler.(interaction.InteractionServer).GetFavoriteVideoIdList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerGetFavoriteVideoIdListArgs() interface{} {
	return interaction.NewInteractionServerGetFavoriteVideoIdListArgs()
}

func newInteractionServerGetFavoriteVideoIdListResult() interface{} {
	return interaction.NewInteractionServerGetFavoriteVideoIdListResult()
}

func commentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerCommentArgs)
	realResult := result.(*interaction.InteractionServerCommentResult)
	success, err := handler.(interaction.InteractionServer).Comment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerCommentArgs() interface{} {
	return interaction.NewInteractionServerCommentArgs()
}

func newInteractionServerCommentResult() interface{} {
	return interaction.NewInteractionServerCommentResult()
}

func getCommentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerGetCommentListArgs)
	realResult := result.(*interaction.InteractionServerGetCommentListResult)
	success, err := handler.(interaction.InteractionServer).GetCommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerGetCommentListArgs() interface{} {
	return interaction.NewInteractionServerGetCommentListArgs()
}

func newInteractionServerGetCommentListResult() interface{} {
	return interaction.NewInteractionServerGetCommentListResult()
}

func getVideoInteractInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerGetVideoInteractInfoArgs)
	realResult := result.(*interaction.InteractionServerGetVideoInteractInfoResult)
	success, err := handler.(interaction.InteractionServer).GetVideoInteractInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerGetVideoInteractInfoArgs() interface{} {
	return interaction.NewInteractionServerGetVideoInteractInfoArgs()
}

func newInteractionServerGetVideoInteractInfoResult() interface{} {
	return interaction.NewInteractionServerGetVideoInteractInfoResult()
}

func batchGetVideoInteractInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerBatchGetVideoInteractInfoArgs)
	realResult := result.(*interaction.InteractionServerBatchGetVideoInteractInfoResult)
	success, err := handler.(interaction.InteractionServer).BatchGetVideoInteractInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerBatchGetVideoInteractInfoArgs() interface{} {
	return interaction.NewInteractionServerBatchGetVideoInteractInfoArgs()
}

func newInteractionServerBatchGetVideoInteractInfoResult() interface{} {
	return interaction.NewInteractionServerBatchGetVideoInteractInfoResult()
}

func getUserInteractInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerGetUserInteractInfoArgs)
	realResult := result.(*interaction.InteractionServerGetUserInteractInfoResult)
	success, err := handler.(interaction.InteractionServer).GetUserInteractInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerGetUserInteractInfoArgs() interface{} {
	return interaction.NewInteractionServerGetUserInteractInfoArgs()
}

func newInteractionServerGetUserInteractInfoResult() interface{} {
	return interaction.NewInteractionServerGetUserInteractInfoResult()
}

func batchGetUserInteractInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServerBatchGetUserInteractInfoArgs)
	realResult := result.(*interaction.InteractionServerBatchGetUserInteractInfoResult)
	success, err := handler.(interaction.InteractionServer).BatchGetUserInteractInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServerBatchGetUserInteractInfoArgs() interface{} {
	return interaction.NewInteractionServerBatchGetUserInteractInfoArgs()
}

func newInteractionServerBatchGetUserInteractInfoResult() interface{} {
	return interaction.NewInteractionServerBatchGetUserInteractInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Favorite(ctx context.Context, req *interaction.DouyinFavoriteActionRequest) (r *interaction.DouyinFavoriteActionResponse, err error) {
	var _args interaction.InteractionServerFavoriteArgs
	_args.Req = req
	var _result interaction.InteractionServerFavoriteResult
	if err = p.c.Call(ctx, "Favorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFavoriteVideoIdList(ctx context.Context, req *interaction.DouyinGetFavoriteVideoIdListRequest) (r *interaction.DouyinGetFavoriteVideoIdListResponse, err error) {
	var _args interaction.InteractionServerGetFavoriteVideoIdListArgs
	_args.Req = req
	var _result interaction.InteractionServerGetFavoriteVideoIdListResult
	if err = p.c.Call(ctx, "GetFavoriteVideoIdList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Comment(ctx context.Context, req *interaction.DouyinCommentActionRequest) (r *interaction.DouyinCommentActionResponse, err error) {
	var _args interaction.InteractionServerCommentArgs
	_args.Req = req
	var _result interaction.InteractionServerCommentResult
	if err = p.c.Call(ctx, "Comment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentList(ctx context.Context, req *interaction.DouyinGetCommentListRequest) (r *interaction.DouyinGetCommentListResponse, err error) {
	var _args interaction.InteractionServerGetCommentListArgs
	_args.Req = req
	var _result interaction.InteractionServerGetCommentListResult
	if err = p.c.Call(ctx, "GetCommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoInteractInfo(ctx context.Context, req *interaction.DouyinGetVideoInteractInfoRequest) (r *interaction.DouyinGetVideoInteractInfoResponse, err error) {
	var _args interaction.InteractionServerGetVideoInteractInfoArgs
	_args.Req = req
	var _result interaction.InteractionServerGetVideoInteractInfoResult
	if err = p.c.Call(ctx, "GetVideoInteractInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetVideoInteractInfo(ctx context.Context, req *interaction.DouyinBatchGetVideoInteractInfoRequest) (r *interaction.DouyinBatchGetVideoInteractInfoResponse, err error) {
	var _args interaction.InteractionServerBatchGetVideoInteractInfoArgs
	_args.Req = req
	var _result interaction.InteractionServerBatchGetVideoInteractInfoResult
	if err = p.c.Call(ctx, "BatchGetVideoInteractInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInteractInfo(ctx context.Context, req *interaction.DouyinGetUserInteractInfoRequest) (r *interaction.DouyinGetUserInteractInfoResponse, err error) {
	var _args interaction.InteractionServerGetUserInteractInfoArgs
	_args.Req = req
	var _result interaction.InteractionServerGetUserInteractInfoResult
	if err = p.c.Call(ctx, "GetUserInteractInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetUserInteractInfo(ctx context.Context, req *interaction.DouyinBatchGetUserInteractInfoRequest) (r *interaction.DouyinBatchGetUserInteractInfoResponse, err error) {
	var _args interaction.InteractionServerBatchGetUserInteractInfoArgs
	_args.Req = req
	var _result interaction.InteractionServerBatchGetUserInteractInfoResult
	if err = p.c.Call(ctx, "BatchGetUserInteractInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
